# Generated by Django 2.1.3 on 2018-11-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='is_cold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='is_health',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='msg',
            name='latitude',
            field=models.FloatField(default=-1, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='longitude',
            field=models.FloatField(default=-1, verbose_name='Longitude'),
        ),
    ]
