# Generated by Django 2.1.3 on 2018-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0002_auto_20181117_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msg',
            old_name='last_added',
            new_name='last_updated',
        ),
    ]
