# Generated by Django 2.1.3 on 2018-11-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_auto_20181118_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
