# Generated by Django 2.1.3 on 2018-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0005_auto_20181118_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='pm25_value',
            field=models.FloatField(null=True),
        ),
    ]
